baseURL = 'https://example.org/'
title = 'Home'

theme = 'hugo-coder'
languageCode = "en"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true

[pagination]
pagerSize = 6

[services]
[services.disqus]
# Enable Disqus comments
# shortname = "yourdiscussshortname"

[markup]
[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
    author = "Khaled Nasr"
    # license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
    description = "Khaled Nasr's personal website"
    keywords = "blog,developer,testautomation,personal"
    info = ["Software engineer in Test"]
    avatarURL = "images/avatar.jpeg"
    #gravatar = "john.doe@example.com"
    dateFormat = "January 2, 2006"
#    since = 2019
    # Git Commit in Footer, uncomment the line below to enable it
#    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    # Right To Left, shift content direction for languages such as Arabic
    rtl = false
    
    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "auto"
    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false
    # Series see also post count
    maxSeeAlsoItems = 5
    # Custom CSS
    customCSS = []
    # Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
    customSCSS = []
    # Custom JS
    customJS = []
    # Custom remote JS files
    customRemoteJS = []

    [taxonomies]
        category = "categories"
        series = "series"
        tag = "tags"
        author = "authors"
    
    [[params.social]]
        name = "Github"
        icon = "fa-brands fa-github fa-2x"
        weight = 1
        url = "https://github.com/Kinasr"
    
    [[params.social]]
        name = "LinkedIn"
        icon = "fa-brands fa-linkedin fa-2x"
        weight = 4
        url = "https://www.linkedin.com/in/kinasr/"
    
    [[params.social]]
        name = "Medium"
        icon = "fa-brands fa-medium fa-2x"
        weight = 5
        url = "https://medium.com/@kinasr95"

[languages]
    [languages.en] 
        languageName = ":uk:"
        lanugateCode = "en"
        weight = 1
        title = "Home"

        [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

#        [[languages.en.menu.main]]
#            name = "Blog"
#            weight = 2
#            url = "posts/"
#
#        [[languages.en.menu.main]]
#            name = "Projects"
#            weight = 3
#            url = "projects/"
#
#        [[languages.en.menu.main]]
#            name = "Contact me"
#            weight = 5
#            url = "contact/"

    [languages.ar]
        languageName = ":egypt:"
        languageCode = "ar"
        weight = 2
        title = "الصفحة الرئيسية"
        [languages.ar.params]
            author = "خالد نصر"
            info = "مهندس اختبار برمجيات"
            description = "Khaled Nasr's personal website"
            keywords = "blog,desenvolvedor,pessoal"
            rtl = true

        [[languages.ar.menu.main]]
            name = "حول"
            weight = 1
            url = "about/"

#        [[languages.ar.menu.main]]
#            name = "Blog"
#            weight = 2
#            url = "posts/"
#
#        [[languages.ar.menu.main]]
#            name = "مشاريع"
#            weight = 3
#            url = "projects/"
#
#        [[languages.ar.menu.main]]
#            name = "التواصل"
#            weight = 5
#            url = "contact/"